substitutions:
  name: "harmonysense8266"
  friendly_name: "Harmony Sense (WiFi + USB)"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

  project:
    name: harmony.sense8266
    version: "1.0"

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

logger:

network:

wifi:

api:

ota:

dashboard_import:
  package_import_url: github://withharmony/esphome/harmonysense8266.yml@main
  import_full_config: false

improv_serial:
  next_url: https://setup.harmony.cedric.kim/sense8266/success
